AuctionHouse/AuctionHouse/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('userProfile.urls')),
    path('', include('website.urls')),
]

AuctionHouse/website/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'website'

urlpatterns = [
    path('live-auction-items/', views.live_auction_items, name='live_auction_items'),
    path('upcoming-auction-items/', views.upcoming_auction_items, name='upcoming_auction_items'),
    path('past-auction-items/', views.past_auction_items, name='past_auction_items'),
    path('auction-detail/<int:item_id>/', views.auction_detail, name='auction_detail'),
    path('search-live-auctions/', views.search_live_auctions, name='search_live_auctions'),
    path('search-upcoming-auctions/', views.search_upcoming_auctions, name='search_upcoming_auctions'),
    path('search-past-auctions/', views.search_past_auctions, name='search_past_auctions'),
    path('create_auction/', views.create_auction, name='create_auction'),
    path('bidding/<int:item_id>/',views.bidding,name="bidding"),
    path('seller_rating/<int:item_id>/', views.seller_rating, name='seller_rating'),
    path('seller/<int:seller_id>/', views.seller_profile, name='seller_profile'),
    # path('rating-already-submitted/', views.rating_already_submitted, name='rating_already_submitted'),
    path('add_to_wishlist/<int:item_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('show_wishlist/', views.show_wishlist, name='show_wishlist'),
    path('winner_me/', views.winner_me, name='winner_me'),
    path('meeting/<int:item_id>/', views.meeting, name='meeting'),
    path('advisors/',views.Advisor_Page,name='advisors'),
    path('advisors/<str:id>',views.Advisor_Inside,name='advisorInside'),
    path('refund/', views.refund_request, name='refund'),
    path('generate-bill/', views.generate_bill, name='generate_bill')

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AuctionHouse/website/forms.py
from django import forms
from .models import *
from django.forms.widgets import TimeInput
from django.core.validators import MinValueValidator

class AuctionSearchForm(forms.Form):
    search_query = forms.CharField(label='Search by title or address', max_length=255)

class AuctionItemForm(forms.ModelForm):
    class Meta:
        model = AuctionItem
        fields = ['title', 'description', 'address', 'start_price', 'image', 'sketchfab_script']
        widgets = {
            'start_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'end_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

class BiddingForm(forms.ModelForm):
    class Meta:
        model = AuctionItem
        fields=['current_bid']
        labels = {
            'current_bid': 'Enter your Bid :',
        }
class MeetingForm(forms.ModelForm):
    class Meta:
        model = Meeting
        fields = ['slot1','slot2', 'slot3']
        widgets = {
            'slot1': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'slot2': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'slot3': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

class RefundRequestForm(forms.ModelForm):
    class Meta:
        model = RefundRequest
        fields = ['reason', 'bank_branch', 'bank_account_number']

AuctionHouse/website/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import AuctionItem,Wishlist, Bid
from .forms import * 
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from userProfile.models import Buyer_Seller, Rating
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.conf import settings
from decimal import Decimal
from django.http import HttpResponse


def live_auction_items(request):
    current_time = timezone.now()
    live_auctions = AuctionItem.objects.filter(approval_status='approved', start_time__lte=current_time, end_time__gt=current_time)
    return render(request, 'live_auction_items.html', {'live_auctions': live_auctions})


def upcoming_auction_items(request):
    current_time = timezone.now()

    upcoming_auctions = AuctionItem.objects.filter(start_time__gt=current_time, end_time__gt=current_time, approval_status='approved')

    return render(request, 'upcoming_auction_items.html', {
        'upcoming_auctions': upcoming_auctions,
    })

def past_auction_items(request=None):
    current_time = timezone.now()
    past_auctions = AuctionItem.objects.filter(start_time__lt=current_time, end_time__lt=current_time, approval_status='approved')

    for auction in past_auctions:
        if not auction.winner:  
            auction.determine_winner() 

    if request:
        return render(request, 'past_auction_items.html', {
            'past_auctions': past_auctions,
        })
        
    else:
        return past_auctions

def auction_detail(request, item_id):
    auction_detail = get_object_or_404(AuctionItem, id=item_id)
    similar_auctions = AuctionItem.objects.filter(
        Q(address__icontains=auction_detail.address) and
        Q(house_type=auction_detail.house_type)
    ).exclude(id=auction_detail.id)

    if (len(similar_auctions) >= 5):
        similar_auctions = similar_auctions[:5]

    if auction_detail.is_past() and not auction_detail.winner:
        auction_detail.determine_winner()
        
    return render(request, 'auction_detail.html', {'auction_detail': auction_detail,'similar_auctions': similar_auctions})


def search_live_auctions(request):
    query = request.GET.get('query', '')
    current_time = timezone.now()
    live_auctions = AuctionItem.objects.filter(
        Q(title__icontains=query) | Q(address__icontains=query),
        end_time__gte=current_time
    )

    return render(request, 'auction_search.html', {'auctions': live_auctions, 'query': query, 'search_type': 'Live Auctions'})

def search_upcoming_auctions(request):
    query = request.GET.get('query', '')
    current_time = timezone.now()

    upcoming_auctions = AuctionItem.objects.filter(
        Q(title__icontains=query) | Q(address__icontains=query),
        start_time__gt=current_time,
    )

    return render(request, 'auction_search.html', {'auctions': upcoming_auctions, 'query': query, 'search_type': 'Upcoming Auctions'})


def search_past_auctions(request):
    query = request.GET.get('query', '')
    current_time = timezone.now()

    past_auctions = AuctionItem.objects.filter(
        Q(title__icontains=query) | Q(address__icontains=query),
        end_time__lt=current_time
    )

    return render(request, 'auction_search.html', {'auctions': past_auctions, 'query': query, 'search_type': 'Past Auctions'})


    
@login_required 
def create_auction(request):
    if request.method == 'POST':
        form = AuctionItemForm(request.POST, request.FILES)
        if form.is_valid():
            auction_item = form.save(commit=False)
            auction_item.created_by = request.user
            auction_item.approval_status = 'pending'
            auction_item.save()
            return redirect('website:auction_detail', item_id=auction_item.id)
    else:
        form = AuctionItemForm()

    return render(request, 'create_auction.html', {'form': form})



@login_required
def bidding(request, item_id):
    auction = get_object_or_404(AuctionItem, id=item_id)

    #The portion of prediction is done by Loknath Saha. It can be found in his contribution part. 
    s_a = AuctionItem.objects.filter(
        Q(address__icontains=auction.address) and
        Q(house_type=auction.house_type) and
        Q(end_time__gt=timezone.now()) and 
        Q(current_bid__gt=0)
    )

    avg_per_sq_feet_price = Decimal(0)
    avg_per_floor_price = Decimal(0)
    count = 0
    
    if s_a.exists():  # Check if the queryset is not empty
        for auctions in s_a:
            if auctions.house_size:
                avg_per_sq_feet_price += (auctions.current_bid / auctions.house_size)
            if auctions.floor_count:
                avg_per_floor_price += (auctions.current_bid / auctions.floor_count)
            count += 1
        
        if count > 0:
            avg_per_floor_price = avg_per_floor_price / count 
            avg_per_sq_feet_price = avg_per_sq_feet_price / count

            predicted_value = (auction.house_size * avg_per_sq_feet_price + auction.floor_count * avg_per_floor_price) / 2
            predicted_value = int(predicted_value)
        else:
            predicted_value = None  # Set predicted_value to None if there are no valid auctions
    else:
        predicted_value = None

    if request.method == "POST":
        form = BiddingForm(request.POST)
        if form.is_valid():
            bid_amount = form.cleaned_data['current_bid']
            highest_bid = Bid.objects.filter(item=auction).order_by('-amount').first()

            if bid_amount >= auction.start_price and (not highest_bid or bid_amount > highest_bid.amount):
                previous_highest_bidder = highest_bid.bidder if highest_bid else None  
                new_bid = Bid.objects.create(bidder=request.user, item=auction, amount=bid_amount)  

                auction.current_bid_by = new_bid.bidder
                auction.current_bid = new_bid.amount
                auction.save()

                if previous_highest_bidder:
                    send_outbid_email(previous_highest_bidder, auction.title, bid_amount)  

                return redirect('website:live_auction_items')
                
            else:
                message = 'Your bid should be greater than the starting price and the current highest bid.'
                return render(request, 'bidding.html', {'auction': auction, 'form': form, 'message': message, 'predicted_value':predicted_value})
    else:
        form = BiddingForm()
    return render(request, 'bidding.html', {'auction': auction, 'form': form, 'predicted_value':predicted_value})

def send_outbid_email(previous_highest_bidder, auction_title, current_highest_bid):
    subject = 'Your bid has been outbid!'
    message = render_to_string('outbid_email.html', {'auction_title': auction_title,'previous_highest_bidder':previous_highest_bidder,'current_highest_bid':current_highest_bid})
    send_mail(subject, message, settings.EMAIL_HOST_USER, [previous_highest_bidder.email])


def seller_rating(request, item_id):
    auction = get_object_or_404(AuctionItem, id=item_id)
    buyer_seller = auction.created_by.buyer_seller

    if request.method == "POST":
        rating_value = int(request.POST.get('rating'))

        # Checking if the user has already rated this item
        if not Rating.objects.filter(buyer_seller=buyer_seller, item=auction).exists():
            rating = Rating.objects.create(buyer_seller=buyer_seller, item=auction, rating=rating_value)
            return redirect('website:live_auction_items')
        else:
            return render(request, 'rating_already_submitted.html', {'buyer_seller': buyer_seller, 'auction': auction})

    return render(request, 'seller_rating.html', {'buyer_seller': buyer_seller, 'auction': auction})

def seller_profile(request, seller_id):
    seller = get_object_or_404(Buyer_Seller, user_id=seller_id)
    return render(request, 'seller_profile.html', {'seller': seller})



def add_to_wishlist(request, item_id):
    wish = get_object_or_404(AuctionItem, id=item_id)
    new_object = Wishlist.objects.create(creator=request.user, wish=wish)
    return redirect('website:show_wishlist')

def show_wishlist(request):
    wishlist = Wishlist.objects.filter(creator=request.user)
    return render(request, 'wishlist.html', {'wishlist': wishlist})

def winner_me(request):
    current_time = timezone.now()

    past_auctions = AuctionItem.objects.filter(start_time__lt=current_time,end_time__lt=current_time,current_bid_by=request.user)

    return render(request, 'winner_me.html', {
        'past_auctions': past_auctions,
    })


def meeting(request, item_id):
    auction = get_object_or_404(AuctionItem, id=item_id)
    if request.method == 'POST':
        form = MeetingForm(request.POST, request.FILES)
        if form.is_valid():
            meeting = form.save(commit=False)
            meeting.item=auction
            meeting.owner=auction.created_by 
            meeting.winner= request.user
            meeting.save()
            title=auction.title
            send_meeting_email(title,meeting.slot1,meeting.slot2,meeting.slot3,meeting.owner,meeting.winner)
            return redirect('userProfile:home')
    else:
        form = MeetingForm()

    return render(request, 'meeting.html', {'form': form})

def send_meeting_email(auction,slot1,slot2,slot3,owner,winner):
    subject = 'Winner wants to schedule a meeting!'
    message = render_to_string('meeting_email.html', {'auction': auction,'slot1':slot1,'slot2':slot2,'slot3':slot3,'owner':owner,'winner':winner})
    send_mail(subject, message, settings.EMAIL_HOST_USER, [owner.email])

# saha
def Advisor_Page(request):

    advisors = User.objects.filter(is_staff=True).exclude(is_superuser=True)

    return render(request,'advisor_page.html',{'advisors':advisors})


def Advisor_Inside(request,id):
    advisor = get_object_or_404(User, id=int(id))

AuctionHouse/website/templates/advisor_inside.html
{% extends 'base.html' %} {% block content %}

<style>
  .advisor-container {
    width: 100%;
    max-width: 1200px;
    margin: 20px auto;
    background-color: white;
    padding: 50px;
    border-radius: 10px;
  }
  .advisor-container p {
    color: black;
    margin: 5px 0;
  }

  .advisor-slot-container {
    margin: 50px auto;
    width: 100%;
    max-width: 1200px;
    background-color: white;
    padding: 10px;
    border-radius: 10px;
  }
  .advisor-slot-container table {
    width: 100%;
  }
  .advisor-slot-container table tr {
    padding: 10px;
    border: 1px solid black;
  }
  .advisor-slot-container table td,
  .advisor-slot-container table th {
    padding: 10px;
    border: 1px solid black;
  }
  .advisor-slot-container table td button {
    border: none;
    padding: 6px 10px;
    font-weight: 600;
    font-size: 16px;
    width: 60%;
    background-color: greenyellow;
  }
</style>
<div class="advisor-container">
  <h3>Advisor name - {{advisor.first_name}} {{advisor.last_name}}</h3>
  <p>Username - {{advisor.username}}</p>
  <p>Email - {{advisor.email}}</p>
</div>

<div class="advisor-slot-container">
  <table>
    <tr>
      <th>Day</th>
      <th>Start</th>
      <th>End</th>
      <th>Remaining Spots</th>
      <th>Book</th>
      <th>Meet Link</th>
    </tr>

    {% for slot in slots %}
    <tr>
      <td>{{slot.day}}</td>
      <td>{{slot.start_time}}</td>
      <td>{{slot.end_time}}</td>
      <td id="remaining-slots-{{ slot.id }}"></td>
      <td>
        {% if request.user in slot.booked_user_list.all %}
        <button class="bookslots" value="{{slot.id}}">Unbook</button>
        {% else %}
        <button class="bookslots" value="{{slot.id}}">Book this slot</button>
        {% endif %}
      </td>
      <td>
        {% if request.user in slot.booked_user_list.all%}

        <a href="{{ slot.meet_link }}">{{ slot.meet_link }}</a>
        {% else %} Not authorized {% endif %}
      </td>
    </tr>
    {% endfor %}
  </table>
</div>

<script type="text/javascript">
  document.querySelectorAll(".bookslots").forEach((btn) => {
    btn.addEventListener("click", async () => {
      await BookSlot(btn.value);
    });
  });

  async function BookSlot(id) {
    //console.log(id);
    const response = await fetch(`/book-slot/${id}`);
    const data = await response.json();
    //console.log(data)
    window.location.reload();
  }
  {% for slot in slots %}
  const remainingSlots{{ slot.id }} = {{ slot.max_user }} - {{ slot.total_user }};
  document.getElementById("remaining-slots-{{ slot.id }}").innerText = remainingSlots{{ slot.id }};
  {% endfor %}
</script>
{% endblock %}

AuctionHouse/website/templates/advisor_page.html
{% extends 'base.html' %}


{% block content %}


<style>
    .advisors-container{
        width: 100%;
        max-width: 1200px;
        margin: 20px auto;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-wrap: wrap;
        
    }
    .advisors-container a {
        text-decoration: none;
        color: black;
    }
    .advisor-card {
        min-height: 250px;
        width: 350px;
        background-color: white;
        margin: 10px;
        border-radius: 10px;
        padding: 15px;
        transition: 0.2s background-color ease-in-out;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        margin: 10px;
    }
    .advisor-card p {
        color: #505050;
        line-height: 2;
    }
    .advisor-card:hover {
        background-color: rgb(235, 235, 235);
    }
</style>


<h3 style="color: white; text-align: center;">Select your desired Advisor</h3>
<div class="advisors-container">
    
    {% for advisor in advisors %}
    <a href="{% url 'website:advisorInside' advisor.id %}">
        <div class="advisor-card">
            
            <h5>Name - {{advisor.first_name}} {{advisor.last_name}}</h5>
            <p>Username - {{advisor.username}}</p>
            <p>Advisor's email - {{advisor.email}}</p>
        </div>
    </a>
    {% endfor %}

    
</div>





{% endblock %}

AuctionHouse/website/templates/auction_detail.html
<!-- auction_detail.html -->
{% extends 'base.html' %}

{% block content %}


  <style>

    .container-col1{
      background-color: rgba(255,255,255,0.7);
      width: 50%;
      padding: 20px;
      border-radius: 10px;
    }
    .container-col1 > img {
      width: 100%;
      height: 100%;
      
      border-radius: 10px;
    } 

    .similar-bid-history-container {
      margin: 50px 0;
      max-width: 1200px;
      width: 100%;
      display: flex;
      justify-content: center;
      align-items: center;
      flex-direction: column;
      
    }
    .similar-bid-history-container a {
      text-decoration: none;
      margin: 10px 0;
      width: 100%;
      
    }
    .similar-bid-history-container > h3 {
      color: rgb(68, 0, 255);
      text-transform: uppercase;
      letter-spacing: 1.5px;
      word-spacing: 7px;
      font-weight: 600;
    }
    .similar-bid-history-card {
      display: flex;
      background-color: azure;
      padding: 20px 10px;
      border-radius: 4px;
      transition: 0.2s background-color ease-in-out;
    }
    .similar-bid-history-card img {
      width: 100%;
      border-radius: 5px;
    }
    .similar-bid-history-card:hover {
      background-color: rgb(228, 228, 228);
    }
  
    .similar-bid-history-card p {
      color: black;
      font-weight: 500;
      font-family: 'Poppins', sans-serif;
    }
    .similar-bid-history-card .card-col1 {
      width: 30%;
      display: flex;
      justify-content: center;
      align-items: center;
      background-color: azure;
      
    }
    .similar-bid-history-card .card-col2 {
      width: 70%;
      padding: 0 20px ;
    }
  </style>
  
  <div class="container mt-4">
    <div class="row">
      <!-- Display Auction Image -->
      <div class="container-col1">
        <img src="{{ auction_detail.image.url }}" alt="{{ auction_detail.title }}" class="img-fluid">
        <br>
        
      </div>
      
      <!-- Auction Details -->
      <div class="col-md-6">
        <div style="background-color: rgba(255, 255, 255, 0.9); padding: 20px; border-radius: 10px;">
          <h2 class="mb-4 text-black">{{ auction_detail.title }} Details</h2>
          
            <p style="color: black;"><strong>Description:</strong> {{ auction_detail.description }}</p>
            <p style="color: black;"><strong>Start Time:</strong> {{ auction_detail.start_time }}</p>
            <p style="color: black;"><strong>End Time:</strong> {{ auction_detail.end_time }}</p>
            <p style="color: black;"><strong>Current Bid:</strong> {{ auction_detail.current_bid }}</p>
            <p style="color: black;"><strong>Address:</strong> {{ auction_detail.address }}</p>
        </div>
      </div>
    </div>
    
    {% if auction_detail.sketchfab_script %}
          <div class="sketchfab-embed-wrapper">
              {{ auction_detail.sketchfab_script|safe }}
          </div>
        {% endif %}
    <!-- Similar bid history -->
    <div class="similar-bid-history-container">
      <h3>View Similar bid history</h3>
      

      {% for auction in similar_auctions %}

      <a href="{% url 'website:auction_detail' auction.id %}">
        <div class="similar-bid-history-card">
          <div class="card-col1"><img src="{{ auction.image.url }}" alt="error"></div>
          <div class="card-col2">
            <h4>{{ auction.title }}</h4>
            <p>{{ auction.description }}</p></div>
            <p>Current Bid: {{ auction.current_bid }}</p>
        </div>
      </a>

      {% endfor %}

      

    </div>
  </div>
{% endblock %}

AuctionHouse/website/templates/live_auction_items.html
<!-- live_auction_items.html -->
{% extends 'base.html' %}

{% block content %}
<div class="flex justify-center items-center mt-6 mb-4">
    <form action="{% url 'website:search_live_auctions' %}" method="GET" class="flex flex-row gap-2">
        <input type="text" placeholder="Search for auctions..." name="query" required class="border border-gray-300 px-4 py-2 rounded-l-md focus:outline-none focus:border-blue-500">
        <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-0 rounded-r-md -ml-1">Search</button>
    </form>
</div>

    <!-- Display Live Auctions -->
    <div class="card-deck">
        <!-- Live Auctions -->
        <div class="card">
            <div class="card-header">
                <h2>Live Auctions</h2>
            </div>
            <div class="card-body">
                <div class="row">
                    {% for auction in live_auctions %}
                    <div class="col-md-4 mb-4">
                        <div class="card">
                            {% if auction.image %}
                            <img src="{{ auction.image.url }}" alt="{{ auction.title }} Image" class="card-img-top">
                            {% endif %}
                            <div class="card-body">
                                <h3 class="card-title">{{ auction.title }}</h3>
                                <p class="card-text text-dark">Seller: <a href="{% url 'website:seller_profile' seller_id=auction.created_by.buyer_seller.user_id %}">{{ auction.created_by.username }}</a></p>
                                <p class="card-text text-dark mb-0">{{ auction.description|truncatewords:15 }}</p>
                                <p class="card-text mb-3">
                                    <small class="text-muted">
                                        Start Time: <span class="start-time">{{ auction.start_time }}</span><br>
                                        End Time: {{ auction.end_time }}
                                    </small>
                                </p>
                                <p class="card-text font-weight-bold text-primary mb-3">
                                    Start Price: {{ auction.start_price}}<br>
                                </p>
                                <p class="card-text font-weight-bold text-primary mb-3">
                                    Current Bid: {{ auction.current_bid }}</p>
                                <a href="{% url 'website:auction_detail' auction.id %}" class="btn btn-sm btn-primary">Details</a>
                                {%if user.is_authenticated%}
                                {%if user.buyer_seller%}
                                {% if user != auction.created_by %}
                                <a href="{% url 'website:bidding' auction.id%}" class="btn btn-sm btn-primary">Bid</a>
                                {%endif%}
                                {%endif%}
                                {%endif%}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

AuctionHouse/website/templates/meeting.html
<!-- create_auction.html -->
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4 rounded" style="background-color: rgba(0, 0, 58, 0.95);">
    <h2 style="color: white;">Select your available slots/h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-success">Request</button>
    </form>
</div>
{% endblock %}

AuctionHouse/website/templates/meeting_email.html
Dear {{owner}},

{{winner}}, winner of the bidding of house-{{auction}}, wants to schedule a meeting with you.

His available slots:
Slot1: {{slot1}}
Slot2: {{slot2}}
Slot3: {{slot3}}

Hope you will have a nice meeting.

Thanks for being with us. If you have any questions or concerns, please don't hesitate to contact us.

Best regards,
Auction House

AuctionHouse/website/templates/past_auction_items.html
<!-- upcoming_auction_items.html -->
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <!-- Search form -->
    <div class="search-container text-center mb-4">
        <form action="{% url 'website:search_upcoming_auctions' %}" method="GET" class="form-inline">
            <input type="text" class="form-control" placeholder="Search for auctions..." name="query" required>
            <button type="submit" class="btn btn-primary">Search</button>
        </form>
    </div>

    <div class="card-deck">
        <!-- Past Auctions -->
        <div class="card">
            <div class="card-header">
                <h2>Past Auctions</h2>
            </div>
            <div class="card-body">
                <div class="row">
                    {% for auction in past_auctions %}
                    <div class="col-md-4 mb-4">
                        <div class="card">
                            {% if auction.image %}
                            <img src="{{ auction.image.url }}" alt="{{ auction.title }} Image" class="card-img-top">
                            {% endif %}
                            <div class="card-body">
                                <h3 class="card-title">{{ auction.title }}</h3>
                                <p class="card-text text-dark">Seller: <a href="{% url 'website:seller_profile' seller_id=auction.created_by.buyer_seller.user_id %}">{{ auction.created_by.username }}</a></p>
                                <p class="card-text text-dark mb-0">{{ auction.description|truncatewords:15 }}</p>
                                {% if auction.winner %}
                                <p class="card-text font-weight-bold text-primary mb-0">
                                    Winner: {{ auction.winner.username }}<br>
                                    Winning Amount: {{ auction.current_bid }}
                                </p>
                                {% else %}
                                <p class="card-text font-weight-bold text-primary mb-0">
                                    No Winner
                                </p>
                                {% endif %}
                                <p class="card-text mb-3">
                                    <small class="text-muted">
                                        Start Time: <span class="start-time">{{ auction.start_time }}</span><br>
                                        End Time: {{ auction.end_time }}
                                    </small>
                                </p>
                                <a href="{% url 'website:auction_detail' auction.id %}" class="btn btn-sm btn-primary">Details</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>    
{% endblock %}

AuctionHouse/website/templates/upcoming_auction_items.html
<!-- upcoming_auction_items.html -->
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <!-- Search form -->
    <div class="search-container text-center mb-4">
        <form action="{% url 'website:search_upcoming_auctions' %}" method="GET" class="form-inline">
            <input type="text" class="form-control" placeholder="Search for auctions..." name="query" required>
            <button type="submit" class="btn btn-primary">Search</button>
        </form>
    </div>

    <!-- Display Upcoming Auctions -->
    <div class="card-deck">
        <!-- Upcoming Auctions -->
        <div class="card">
            <div class="card-header">
                <h2>Upcoming Auctions</h2>
            </div>
            <div class="card-body">
                <div class="row">
                    {% for auction in upcoming_auctions %}
                    <div class="col-md-4 mb-4">
                        <div class="card">
                            {% if auction.image %}
                            <img src="{{ auction.image.url }}" alt="{{ auction.title }} Image" class="card-img-top">
                            {% endif %}
                            <div class="card-body">
                                <h3 class="card-title">{{ auction.title }}</h3>
                                <h10 class="card-text text-dark">Seller: {{ auction.created_by.username }}</h10><br>
                                <p class="card-text text-dark mb-0">{{ auction.description|truncatewords:15 }}</p>
                                <p class="card-text font-weight-bold text-primary mb-0">
                                    Current Bid: {{ auction.current_bid }}
                                </p>
                                <p class="card-text mb-3">
                                    <small class="text-muted">
                                        Start Time: <span class="start-time">{{ auction.start_time }}</span><br>
                                        End Time: {{ auction.end_time }}
                                    </small>
                                </p>
                                <a href="{% url 'website:auction_detail' auction.id %}" class="btn btn-sm btn-primary">Details</a>
                                {%if user.is_authenticated%}
                                {%if user.buyer_seller%}
                                {% if user != auction.created_by %}
                                <a href="{% url 'website:add_to_wishlist' auction.id %}" class="btn btn-sm btn-primary">Add to Wishlist</a>
                                {%endif%}
                                {%endif%}
                                {%endif%}
                                
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}