AuctionHouse/AuctionHouse/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('userProfile.urls')),
    path('', include('website.urls')),
]

AuctionHouse/userProfile/urls.py
from django.urls import path
from . import views

app_name = 'userProfile'

urlpatterns=[
    path('',views.home,name="home"),
    path('register/',views.register,name="register"),
    path("aboutUs/",views.aboutUs,name="aboutUs"),
    path("profile_view/",views.profile_view,name="profile_view"),
    path("profile_update/",views.profile_update,name="profile_update"),
    path("profile_update_page/",views.profile_update_page,name="profile_update_page"),
    path('manage-slot/',views.ManageSlot, name='manageSlot'),
    path('create-slot/',views.CreateSlot, name='createSlot'),
    path('update-slot/<str:id>',views.UpdateSlot,name='updateSlot'),
    path('delete-slot/<str:id>',views.DeleteSlot, name='deleteSlot'),
    path('book-slot/<str:id>',views.BookSlot,name='bookSlot'),
    path('search/', views.search_properties, name='search_properties'),
    path('otp-verification/', views.otp_verification, name='otp_verification')
    ]

AuctionHouse/website/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'website'

urlpatterns = [
    path('live-auction-items/', views.live_auction_items, name='live_auction_items'),
    path('upcoming-auction-items/', views.upcoming_auction_items, name='upcoming_auction_items'),
    path('past-auction-items/', views.past_auction_items, name='past_auction_items'),
    path('auction-detail/<int:item_id>/', views.auction_detail, name='auction_detail'),
    path('search-live-auctions/', views.search_live_auctions, name='search_live_auctions'),
    path('search-upcoming-auctions/', views.search_upcoming_auctions, name='search_upcoming_auctions'),
    path('search-past-auctions/', views.search_past_auctions, name='search_past_auctions'),
    path('create_auction/', views.create_auction, name='create_auction'),
    path('bidding/<int:item_id>/',views.bidding,name="bidding"),
    path('seller_rating/<int:item_id>/', views.seller_rating, name='seller_rating'),
    path('seller/<int:seller_id>/', views.seller_profile, name='seller_profile'),
    # path('rating-already-submitted/', views.rating_already_submitted, name='rating_already_submitted'),
    path('add_to_wishlist/<int:item_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('show_wishlist/', views.show_wishlist, name='show_wishlist'),
    path('winner_me/', views.winner_me, name='winner_me'),
    path('meeting/<int:item_id>/', views.meeting, name='meeting'),
    path('advisors/',views.Advisor_Page,name='advisors'),
    path('advisors/<str:id>',views.Advisor_Inside,name='advisorInside'),
    path('refund/', views.refund_request, name='refund'),
    path('generate-bill/', views.generate_bill, name='generate_bill')

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AuctionHouse/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
    crossorigin="anonymous">

  <!-- Bootstrap JS with Popper.js -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
    integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
    integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
    crossorigin="anonymous"></script>
  <link
      href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css"
      rel="stylesheet"
    />
  <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
      rel="stylesheet"
    />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">

  {% load static %}
  <link rel="stylesheet" href="{% static 'base.css' %}">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
  <title>Auction House</title>
</head>

<body class="flex flex-col min-h-screen">
  <nav class="navbar navbar-expand-lg relative">
    <div class="flex justify-between  w-full ">
      <div class="flex-shrink-0 flex items-center absolute top-2 left-2">
        <a
          href="/"
          class="rounded-lg border-2 border-b-4 border-r-4 border-white px-2 py-1 text-2xl text-white font-bold hover:text-indigo-600"
        >
          <i class="fas fa-home mx-1"></i> Auction House
        </a>
      </div>
      <div class="container mx-auto ">
        <div class=" text-right">
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
        </div>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'userProfile:home' %}">Home</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'userProfile:aboutUs' %}">About Us</a>
              </li>
              {% if user.is_authenticated %}
                  {% if request.user.is_staff%}
                      {% if request.user.is_superuser %}
                          <li class="nav-item">
                              <a class="nav-link" aria-current="page" href="">Admin Panel</a>
                          </li>
                      {% else %}
                          <li class="nav-item">
                              <a class="nav-link" aria-current="page" href="{% url 'userProfile:manageSlot' %}">Manage Slot</a>
                          </li>
                      {% endif %}
                  
                  {% endif %}
                  
                {% endif %}  

              {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="profileDropdown" role="button" data-bs-toggle="dropdown"
                          aria-haspopup="true" aria-expanded="false">
                          Profile
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="profileDropdown">
                          <li><a class="dropdown-item" href="{% url 'userProfile:profile_view' %}">View Profile</a></li>
                          <li><a class="dropdown-item" href="{% url 'website:show_wishlist' %}"> Wishlist</a></li>
                          <li><a class="dropdown-item" href="{% url 'website:winner_me' %}"> Winning bids</a></li>
                          <li><a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a></li>
                      </ul>
                  </li>
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="auctionDropdown" role="button" data-bs-toggle="dropdown"
                          aria-haspopup="true" aria-expanded="false">
                          Auction
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="auctionDropdown">
                          <li><a class="dropdown-item" href="{% url 'website:upcoming_auction_items' %}">Upcoming Bidding</a></li>
                          <li><a class="dropdown-item" href="{% url 'website:live_auction_items' %}">Live Bidding</a></li>
                          <li><a class="dropdown-item" href="{% url 'website:past_auction_items' %}">Past Biddings</a></li>
                      </ul>
                  </li>
              
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'website:advisors' %}">Financial Advice</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'website:create_auction' %}">Sell House</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'website:refund' %}">Refund</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'website:generate_bill' %}">Generate Bill</a>
              </li>
            
          {% else %}
              <li class="nav-item">
                  <a href="{%url 'account_signup'%}" class="nav-link">SignUp</a>
              </li>
              <li class="nav-item">  
                  <a href="{%url 'account_login'%}" class="nav-link">Login</a>
              </li>
              {% endif %}
          </ul>

        </div>
      </div>
    </div>
  </nav>
  <div class="flex-1 container">
    {% block content %}
      <p>This is the base template content.</p>
    {% endblock %}
  </div>
  <footer style="background-color: #001f3f;" class="text-white mt-4">
      <div class="mx-auto py-8 px-8 flex flex-wrap justify-between items-start">
        <div class="w-full lg:w-2/3 pr-4 mb-4 lg:mb-0">
          <div class="mb-4">
            <h3 class="text-sm font-semibold mb-2">Price Information</h3>
            <p class="text-xs text-left mb-2">
              *Guides are provided as an indication of each seller's minimum
              expectation. They are not necessarily figures which a property
              will sell for and may change at any time prior to the auction.
              Each property will be offered subject to a Reserve (a figure below
              which the Auctioneer cannot sell the property during the auction)
              which we expect will be set within the Guide Range or no more than
              10% above a single figure Guide.
            </p>
          </div>
          <div class="mb-4">
            <h3 class="text-sm font-semibold mb-2">
              Additional Fees Information
            </h3>
            <p class="text-xs text-left mb-2">
              *Please be aware there may be additional fees payable on top of
              the final sale price. This include and are not limited to
              administration charges and buyer's premium fees payable on
              exchange, and disbursements payable on completion. Please ensure
              you check the property information page for a list of any relevant
              additional fees as well as reading the legal pack for any
              disbursements.
            </p>
          </div>
        </div>
        <div
          class="w-full my-auto lg:w-1/3 flex flex-col justify-center items-center border-white lg:border-l-2"
        >
          <div class="mb-1 flex flex-col justify-center items-center">
            <div class="flex justify-center lg:justify-end">
              <a
                title="FB"
                href="#"
                target="_blank"
                rel="noopener noreferrer"
                class="btn btn-outline-white mr-2"
              >
                <i class="fab fa-facebook-f mx-2"></i>
              </a>
              <a
                title="Twit"
                href="#"
                target="_blank"
                rel="noopener noreferrer"
                class="btn btn-outline-white mx-2"
              >
                <i class="fab fa-twitter mx-2"></i>
              </a>
              <a
                title="Insta"
                href="#"
                target="_blank"
                rel="noopener noreferrer"
                class="btn btn-outline-white mr-2"
              >
                <i class="fab fa-instagram mx-2"></i>
              </a>
            </div>
            <h3 class="text-lg font-semibold mb-2 text-center lg:text-left">
              Connect with us
            </h3>
          </div>
          <div class="mb-1">
            <div class="flex justify-center lg:justify-end">
              <a
                href="/"
                class="mx-4 text-white hover:text-gray-200 border-b-2 border-transparent hover:border-white"
              >
                Terms & Conditions
              </a>
              <p>|</p>
              <a
                href="/"
                class="mx-4 text-white hover:text-gray-200 border-b-2 border-transparent hover:border-white"
              >
                Privacy Policy
              </a>
            </div>
          </div>
          <div class="text-center lg:text-right">
            <p>&copy; 2024 Auction House G6_471</p>
          </div>
        </div>
      </div>
  </footer>
</body>

</html>

 