AuctionHouse/AuctionHouse/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('userProfile.urls')),
    path('', include('website.urls')),
]

AuctionHouse/userProfile/urls.py
from django.urls import path
from . import views

app_name = 'userProfile'

urlpatterns=[
    path('',views.home,name="home"),
    path('register/',views.register,name="register"),
    path("aboutUs/",views.aboutUs,name="aboutUs"),
    path("profile_view/",views.profile_view,name="profile_view"),
    path("profile_update/",views.profile_update,name="profile_update"),
    path("profile_update_page/",views.profile_update_page,name="profile_update_page"),
    path('manage-slot/',views.ManageSlot, name='manageSlot'),
    path('create-slot/',views.CreateSlot, name='createSlot'),
    path('update-slot/<str:id>',views.UpdateSlot,name='updateSlot'),
    path('delete-slot/<str:id>',views.DeleteSlot, name='deleteSlot'),
    path('book-slot/<str:id>',views.BookSlot,name='bookSlot'),
    path('search/', views.search_properties, name='search_properties'),
    path('otp-verification/', views.otp_verification, name='otp_verification')
    ]

AuctionHouse/website/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'website'

urlpatterns = [
    path('live-auction-items/', views.live_auction_items, name='live_auction_items'),
    path('upcoming-auction-items/', views.upcoming_auction_items, name='upcoming_auction_items'),
    path('past-auction-items/', views.past_auction_items, name='past_auction_items'),
    path('auction-detail/<int:item_id>/', views.auction_detail, name='auction_detail'),
    path('search-live-auctions/', views.search_live_auctions, name='search_live_auctions'),
    path('search-upcoming-auctions/', views.search_upcoming_auctions, name='search_upcoming_auctions'),
    path('search-past-auctions/', views.search_past_auctions, name='search_past_auctions'),
    path('create_auction/', views.create_auction, name='create_auction'),
    path('bidding/<int:item_id>/',views.bidding,name="bidding"),
    path('seller_rating/<int:item_id>/', views.seller_rating, name='seller_rating'),
    path('seller/<int:seller_id>/', views.seller_profile, name='seller_profile'),
    # path('rating-already-submitted/', views.rating_already_submitted, name='rating_already_submitted'),
    path('add_to_wishlist/<int:item_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('show_wishlist/', views.show_wishlist, name='show_wishlist'),
    path('winner_me/', views.winner_me, name='winner_me'),
    path('meeting/<int:item_id>/', views.meeting, name='meeting'),
    path('advisors/',views.Advisor_Page,name='advisors'),
    path('advisors/<str:id>',views.Advisor_Inside,name='advisorInside'),
    path('refund/', views.refund_request, name='refund'),
    path('generate-bill/', views.generate_bill, name='generate_bill')

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AuctionHouse/userProfile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import EmailValidator
from website.models import AuctionItem
from django.db.models import Avg

class Buyer_Seller(models.Model):
    user=models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    phone=models.CharField(max_length=11)
    address=models.CharField(max_length=100)
    ratings_sum = models.IntegerField(default=0)
    ratings_count = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

    def average_rating(self):
        ratings = Rating.objects.filter(buyer_seller=self)
        avg_rating = ratings.aggregate(Avg('rating'))['rating__avg']
        return avg_rating if avg_rating else 0

class Rating(models.Model):
    buyer_seller = models.ForeignKey(Buyer_Seller, on_delete=models.CASCADE)
    item = models.ForeignKey(AuctionItem, on_delete=models.CASCADE)
    rating = models.IntegerField()

    class Meta:
        unique_together = ('buyer_seller', 'item')  # Ensures one review per buyer per item

    def __str__(self):
        return f"{self.buyer_seller.user.username}'s rating for item {self.item}: {self.rating}"

AuctionHouse/userProfile/forms.py
from django import forms
from . models import *
from website.models import *

class RegitrationForm(forms.ModelForm):
    class Meta:
        model= Buyer_Seller
        fields=['phone','address']

class CreateSlotForm(forms.ModelForm):
    class Meta:
        model = AdvisorSlot
        fields = "__all__"
        


class UpdateSlotForm(forms.ModelForm):
    class Meta:
        model = AdvisorSlot
        fields = ['day','start_time','end_time','message','meet_link','max_user']

AuctionHouse/userProfile/views.py
from django.shortcuts import render,redirect
from .forms import *
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth import logout
import random
from django.core.mail import send_mail
from django.contrib import messages
from django.conf import settings
from django.http import JsonResponse


# Create your views here.
def home(request):
    return render(request,'userProfile/home.html')

def aboutUs(request):
    return render(request,'userProfile/aboutUs.html')  

def register(request):
    if request.method=="POST":
        form=RegitrationForm(request.POST)
        if form.is_valid():
            var=form.save(commit=False)
            var.user=request.user
            var.save()
            return redirect ('userProfile:home')
    else:
        form=RegitrationForm()
    return render(request,'userProfile/register.html',{'form':form})

def profile_view(request):
    profile = request.user.buyer_seller
    return render(request,'userProfile/profile_view.html',{'profile':profile})

"""
def profile_update_page(request):
    profile = Buyer_Seller.objects.get(user=request.user)

    if request.method == 'POST':
        form = RegitrationForm(request.POST, instance=profile)
        if form.is_valid():
            var=form.save(commit=False)
            var.user=request.user
            var.save()
            return redirect("userProfile:profile_view")
    else:
        form = RegitrationForm(instance=profile)

    return render(request, 'userProfile/profile_update.html', {'form': form})

"""

def profile_update(request):
    if request.user.is_authenticated:
        # To generate OTP
        otp = ''.join(random.choices('0123456789', k=6))
        send_mail(
            'OTP for Profile Update',
            f'Your OTP for profile update is: {otp}',
            settings.EMAIL_HOST_USER,
            [request.user.email],
            fail_silently=False,
        )
        # To store the OTP in the session
        request.session['otp'] = otp
        return redirect("userProfile:otp_verification")
    else:
        return redirect("userProfile:home")  

def otp_verification(request):
    if request.method == 'POST':
        entered_otp = request.POST.get('otp')
        otp_in_session = request.session.get('otp')
        if entered_otp == otp_in_session:
            del request.session['otp']  # To remove the OTP from the session
            return redirect('userProfile:profile_update_page')
        else:
            messages.error(request, 'Invalid OTP. Please try again.')
            return redirect("userProfile:otp_verification")

    return render(request, 'userProfile/otp_verification.html')

def profile_update_page(request):
    profile = Buyer_Seller.objects.get(user=request.user)

    if request.method == 'POST':
        form = RegitrationForm(request.POST, instance=profile)
        if form.is_valid():
            var = form.save(commit=False)
            var.user = request.user
            var.save()
            return redirect("userProfile:profile_view")
    else:
        form = RegitrationForm(instance=profile)

    return render(request, 'userProfile/profile_update.html', {'form': form})


def ManageSlot(request):
    role = ProtectRole(request,'advisor')

    if not role:
        return redirect('/')

    slots = AdvisorSlot.objects.filter(user=request.user)

    # print(slots[0].booked_user_list.all())

    return render(request,'userProfile/manage_slot.html',{'slots':slots})


def CreateSlot(request):
    role = ProtectRole(request,'advisor')

    if not role:
        return redirect('/')


    if request.method == 'POST':
        form = CreateSlotForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/manage-slot')
    return render(request,'userProfile/create_slot.html',{})


def UpdateSlot(request, id):
    role = ProtectRole(request,'advisor')

    if not role:
        return redirect('/')
    slot = AdvisorSlot.objects.get(id=int(id))

    form = UpdateSlotForm(instance=slot)


    if request.method == 'POST':

        form2 = UpdateSlotForm(request.POST, instance=slot)

        if form2.is_valid():
            form2.save()
            return redirect('/manage-slot')

    return render(request,'userProfile/update_slot.html',{'slot':slot,'form':form})


def DeleteSlot(request, id):
    role = ProtectRole(request,'advisor')

    if not role:
        return redirect('/')

    slot = AdvisorSlot.objects.get(id=int(id))

    slot.delete()

    return redirect('/manage-slot')


def ProtectRole(request, role):

    if not request.user.is_authenticated:
        return False

    elif role == 'admin':
        if not request.user.is_superuser:
            return False
    
    elif role == 'advisor':
        if not request.user.is_staff:
            return False

    return True


def BookSlot(request, id):
    if request.user.is_authenticated:
        slot = AdvisorSlot.objects.get(id=int(id))
        if slot.total_user+1 > slot.max_user:
            return JsonResponse({"Error":"Max capacity reached"})
        else:
            if request.user in slot.booked_user_list.all():
                slot.total_user -= 1
                slot.booked_user_list.remove(request.user)
                slot.save()

                return JsonResponse({'success':'Slot Unbooked successfully'})
            else:
                slot.total_user += 1
                slot.booked_user_list.add(request.user)
                slot.save()

                return JsonResponse({'success':'Slot booked successfully'})

    else:
        return JsonResponse({"Error":"You need to login first"})
    
def search_properties(request):
    if request.method == 'GET':
        location = request.GET.get('location')
        property_type = request.GET.get('property_type')
        price_range = request.GET.get('price_range')
        min_size = request.GET.get('min_size')

        items = AuctionItem.objects.all()
        if location:
            items = items.filter(address__icontains=location)
        if property_type:
            items = items.filter(house_type=property_type)
        if price_range:
            items = items.filter(start_price__lte=price_range)
        if min_size:
            items = items.filter(house_size__gte=min_size)

        return render(request, 'userProfile/search_results.html', {'items': items})

    return render(request, 'home.html')

AuctionHouse/userProfile/templates/userProfile/aboutUs.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <br>
   
    <div class="container d-flex justify-content-center align-items-center">
        <div class="card p-4 border-primary rounded shadow" style="background-color: rgba(249, 240, 223, 0.5); width: 500px;">
            <h4 style="margin-left: 5%; margin-bottom: 12px; font-size: 30px; font-weight: bold; background: linear-gradient(135deg, rgb(40, 42, 95), rgb(106, 106, 203),rgb(30, 31, 70)); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">
                Welcome to Auction House
            </h4>
            <p class="card-text"  
            style="text-align: center;
            margin-bottom: 20px; 
            font-size: 20px; 
            font-weight: 500;
            color: rgb(40, 42, 95)"> <!-- Adjusted the inline style here -->
            "Your premier destination for a seamless and dynamic real estate experience.Dive into the world of property auctions, where sellers can showcase their homes and buyers can engage in competitive bidding to find their dream property. Elevate your journey with our exclusive feature to book appointments with experienced financial advisors, ensuring you make informed decisions. Discover the future of real estate transactions with us."</p>
        </div>
    </div>
{% endblock %}

AuctionHouse/userProfile/templates/userProfile/create_slot.html
{% extends 'base.html' %} {% block content %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title></title>
    <style>
      body {
        font-family: Arial, sans-serif;
        background: transparent;
        margin: 0;
        padding: 0;
      }

      .slot-container {
        max-width: 500px;
        width: 100%;
        margin: 50px auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
      }

      .slot-container form {
        width: 100%;
      }
      label {
        font-weight: bold;
      }

      input,
      select,
      textarea {
        width: 100%;
        padding: 8px;
        margin: 5px 0;
        box-sizing: border-box;
        border: 1px solid #ccc;
        border-radius: 4px;
      }

      input[type="submit"] {
        margin-left: 50px;
        width: 80%;
        background-color: #4caf50;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
      }

      input[type="submit"]:hover {
        background-color: #45a049;
      }
    </style>
  </head>

  <body>
    <div class="slot-container">
      <h2>Create New Slot</h2>
      <form action="" method="post">
        {% csrf_token %}

        <select style="display: none" name="user" required id="id_user">
          <option value="" selected>---------</option>
          <option value="{{request.user.id}}" selected>{{request.user}}</option>
        </select>

        <label for="day">Day:</label>
        <select id="day" name="day">
          <option value="Saturday">Saturday</option>
          <option value="Sunday">Sunday</option>
          <option value="Monday">Monday</option>
          <option value="Tuesday">Tuesday</option>
          <option value="Wednesday">Wednesday</option>
          <option value="Thursday">Thursday</option>
        </select>

        <label for="start_time">Start Time:</label>
        <input type="time" id="start_time" name="start_time" />

        <label for="end_time">End Time:</label>
        <input type="time" id="end_time" name="end_time" />

        <label for="message">Message:</label>
        <textarea
          id="message"
          name="message"
          placeholder="Enter message"
        ></textarea>

        <label for="meet_link">Meeting Link:</label>
        <input
          type="text"
          id="meet_link"
          name="meet_link"
          placeholder="Enter meeting link"
          default="Will be provided when the slot is started"
        />
        <label for="max_user">Max Users:</label>
        <input type="number" id="max_user" name="max_user" min="1" />

        <input type="submit" value="Create Slot" />
      </form>
    </div>
  </body>
</html>

{% endblock %}

AuctionHouse/userProfile/templates/userProfile/home.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6 text-center">
      <h1 class="animate__animated animate__fadeIn animate__delay-1s">Welcome to Auction House</h1>
      <h6 class="animate__animated animate__fadeIn animate__delay-2s">Where Homes Meet Opportunities</h6>
      <div class="flex justify-center animate__animated animate__fadeIn animate__delay-3s">
        <div class="max-w-lg border border-gray-300 p-8 rounded-lg shadow-lg">
          <h2 class="text-3xl text-indigo-500 font-bold mb-4 hover:text-indigo-700">Find Your Next Property at Auction</h2>
          <form action="{% url 'userProfile:search_properties' %}" method="GET" class="items-center">
            <div class="mb-4 text-left">
              <label for="location" class="block text-[10px] font-medium text-black/80">Location:</label>
              <input type="text" id="location" name="location" class="form-input mt-1 block w-full rounded-md shadow-sm bg-gray-100 border-2 border-black p-1 " placeholder="Enter location...">
            </div>
            <div class="mb-4 text-left">
              <label for="property_type" class="block text-[10px] font-medium text-black/80">Property Type:</label>
              <select id="property_type" name="property_type" class="form-select mt-1 block w-full rounded-md shadow-sm bg-gray-100 border-2 border-black p-1">
                <option value="">Select property type...</option>
                <option value="Bunglow">Bunglow</option>
                <option value="Duplex">Duplex</option>
                <option value="Flat">Flat</option>
                <option value="Normal">Normal</option>
              </select>
            </div>
            <div class="mb-4 text-left">
              <label for="price_range" class="block text-[10px] font-medium text-black/80">Price Range:</label>
              <select id="price_range" name="price_range" class="form-select mt-1 block w-full rounded-md shadow-sm bg-gray-100 border-2 border-black p-1 shadow-sm">
                <option value="">Select price range...</option>
                <option value="500000">500,000</option>
                <option value="1000000">1,000,000</option>
                <option value="2000000">2,000,000</option>
                <option value="4000000">+4,000,000</option>
              </select>
            </div>
            <div class="mb-4 text-left">
              <label for="min_size" class="block text-[10px] font-medium text-black/80">Min. Size:</label>
              <select id="min_size" name="min_size" class="form-select mt-1 block w-full rounded-md shadow-sm bg-gray-100 border-2 border-black p-1 shadow-sm">
                <option value="">Select minimum size...</option>
                <option value="1000">1,000 sqft</option>
                <option value="2000">2,000 sqft</option>
                <option value="3000">3,000 sqft</option>
                <option value="5000">+5,000 sqft</option>
              </select>
            </div>
            <div class="text-center">
              <button type="submit" class=" items-center px-4 py-2 border border-transparent rounded-md font-semibold text-sm text-white bg-indigo-500 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 ml-0">Search</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

AuctionHouse/userProfile/templates/userProfile/manage_slot.html
{% extends 'base.html' %} {% block content %}

<style>
  .advisor-slot-container {
    margin: 50px auto;
    width: 100%;
    max-width: 1200px;
    background-color: white;
    padding: 10px;
    border-radius: 10px;
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
  }
  .advisor-slot-container table {
    width: 100%;
  }
  .advisor-slot-container table tr {
    padding: 10px;
    border: 1px solid black;
  }
  .advisor-slot-container table td,
  .advisor-slot-container table th {
    padding: 10px;
    border: 1px solid black;
  }
  .advisor-slot-container table td button {
    border: none;
    padding: 6px 10px;
    font-weight: 600;
    font-size: 16px;
    width: 20%;
  }
  .update {
    background-color: greenyellow;
  }
  .delete {
    background-color: black;
    color: white;
  }
  .create-slot {
    margin: 15px 0;
    padding: 6px 10px;
    font-size: 16px;
    font-weight: 600;
    color: white;
    background-color: black;
    border-radius: 4px;
    border: none;
    border: 2px solid black;
    transition: 0.4s;
    width: 100%;
  }
  .create-slot:hover {
    background-color: white;
    color: black;
  }
  .advisor-slot-container > a {
    width: 100%;
  }
</style>

<div class="manage-slot-container">
  <div class="advisor-slot-container">
    <h3 style="color: black; text-align: center">Manage your slots</h3>
    <table>
      <tr>
        <th>Day</th>
        <th>Start</th>
        <th>End</th>
        <th>Max. User</th>
        <th>Manage</th>
      </tr>

      {% for slot in slots %}
      <tr>
        <td>{{slot.day}}</td>
        <td>{{slot.start_time}}</td>
        <td>{{slot.end_time}}</td>
        <td>{{slot.max_user}}</td>
        <td>
          <a href="{% url 'userProfile:updateSlot' slot.id %}"
            ><button class="update">Update</button></a
          >
          <a href="{% url 'userProfile:deleteSlot' slot.id %}"
            ><button class="delete">Delete</button></a
          >
        </td>
      </tr>
      {% endfor %}
    </table>
    <a href="{% url 'userProfile:createSlot' %}"
      ><button class="create-slot">Create Slot</button></a
    >
  </div>
</div>

{% endblock %}

AuctionHouse/userProfile/templates/userProfile/otp_verification.html
{% extends 'base.html' %}

{% block content %}
<style>


    .container {

        justify-content: center;
        align-items: center;
        text-align: center;
    }
 
    .error-messages {
        margin-top: 10px;
        text-align: center;
    }

    .error-message {
        background-color: #f8d7da;
        color: #721c24;
        padding: 10px;
        border-radius: 5px;
        margin-bottom: 5px;
        width: 50%;
        margin-left: 25%;
    }
</style>
<br><br>
<div class="container">
    <h1>OTP Verification</h1>
    <form action="{% url 'userProfile:otp_verification' %}" method="POST">
        {% csrf_token %}
        <label for="otp" style="font-weight: 500;">Enter OTP</label><br>
        <input type="text" id="otp" name="otp" required><br><br>
        <input style="background-color: rgb(8, 8, 60); color: white;" type="submit" value="Verify">
    </form>
    {% if messages %}
        <div class="error-messages">
            {% for message in messages %}
                <div class="error-message">{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}
</div>

{% endblock %}

AuctionHouse/userProfile/templates/userProfile/profile_update.html
{% extends 'base.html' %}

{% block content %}
    <style>
        
        input,
        select,
        textarea {
            width: 90%;
            padding: 6px;
            margin: 4px 0;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
            color: black;
        }
    </style>
    <br>
    <br>
    <br>
    <div class="container d-flex justify-content-center align-items-center">
    <div class="card p-4 border-primary rounded shadow" style="background-color: #001f3f; max-width: 400px;">
        <h2 style="text-align: center; color: whitesmoke;">Update Profile</h2><br><br>
        <form method="post" class="black-inputs">
            {% csrf_token %}
            {{ form.as_p }}
            <input style="text-align: center; margin-left: 25%;" type="submit" value="submit">
        </form>

    </div>
</div>
<br>
{% endblock %}

AuctionHouse/userProfile/templates/userProfile/profile_view.html
{% extends 'base.html' %}

{% block content %}

    <style>
        /* Custom CSS for the profile view */
        .profile-card {
            background-color: rgba(249, 240, 223, 0.5); /* Transparent background color */
            padding: 20px; /* Padding */
            border-radius: 15px; /* Rounded corners */
            box-shadow: 0 4px 8px 0 rgba(98, 62, 11, 0.2); /* Shadow effect */
            color: white; /* Text color */
            width: 360px; /* Card width */
            align-items: left; /* Center content vertically */
            align-self: center; /* Center card horizontally */
        }

        /* Custom CSS for the profile card title */
        .profile-card p {
            text-align: left; /* Center text */
            margin-bottom: 20px; /* Bottom margin */
            font-size: 20px; /* Font size */
            font-weight: 10; /* Bold text */
            color: rgb(40, 42, 95);
        }

        /* Custom CSS for profile details */
        .profile-details {
            text-align: left; /* Align text to the left */
            margin-bottom: 10px; /* Bottom margin */
        }

        /* Custom CSS for update button */
        .update-button {
            background: linear-gradient(130deg, rgb(40, 42, 95), rgb(103, 103, 134), rgb(40, 42, 95)); /* Gradient background */
            border: none; /* Remove border */
            color: white; /* Text color */
            padding: 10px 25px; /* Padding */
            text-align: center; /* Center text */
            text-decoration: none; /* Remove underline */
            display: inline-block; /* Make it inline block */
            font-size: 18px; /* Font size */
            border-radius: 10px; /* Rounded corners */
            cursor: pointer; /* Add cursor pointer */
            transition: background-color 0.3s; /* Add transition for hover effect */
        }

        /* Hover effect for update button */
        .update-button:hover {
            background-color: #001f3f; /* Darker gradient background color */
        }
    </style>

    <br><br><br><br>
    {% if user.is_authenticated %}
    <div class="container d-flex justify-content-center align-items-center">
        <div class="card p-4 border-primary rounded shadow profile-card" style="width: 400px; ">
            <h4 style="margin-left: 30%; margin-bottom: 12px; font-size: 30px; font-weight: bold; background: linear-gradient(130deg, rgb(40, 42, 95), rgb(99, 99, 143), rgb(24, 25, 57)); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">
                My Profile
            </h4><br>
            <p><span style="font-weight: bold;">Name: </span> {{ profile.user.username |title }}</p>
            <p><span style="font-weight: bold;">Email: </span> {{ profile.user.email }}</p>
            <p><span style="font-weight: bold;">Phone: </span>{{ profile.phone }}</p>
            <p><span style="font-weight: bold;">Address: </span>{{ profile.address }}</p>
            <a href="{% url 'userProfile:profile_update' %}" class="btn btn-primary update-button" style="margin-left: 30%;">Update</a>
        </div>
    </div><br>
    {% else %}
    <div class="container d-flex justify-content-center align-items-center">
        <div class="card p-4 border-primary rounded shadow" style="background-color: #001f3f; width: 350px; ">
            <h2 class="card-title text-light mb-4">Welcome to Auction House</h2>
            <p>Please register first</p>
        </div>
    </div>
    {% endif %}
{% endblock %}

AuctionHouse/userProfile/templates/userProfile/register.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <br>
    <br>
    <br>
    <div class="container d-flex justify-content-center align-items-center">
    <div class="card p-4 border-primary rounded shadow" style="background-color: #001f3f; max-width: 400px;">
        <h1 style="color: white; font-size: 20px;">Please fill up the form to buy or sell property from our website</h1><br>
        {%if user.is_authenticated%}
        <form method="POST">
            {%csrf_token%}
            {{form.as_p}}
            <input type="submit" value="submit">
        </form>
    {%endif%}

    </div>
</div>
{% endblock %}

AuctionHouse/userProfile/templates/userProfile/search_results.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5">
  <h1>Search Results</h1>
  <div class="row">
    {% for item in items %}
    <div class="col-md-4">
      <div class="card">
        <img src="{{ item.image.url }}" class="card-img-top" alt="{{ item.title }}">
        <div class="card-body">
          <h5 class="card-title">{{ item.title }}</h5>
          <p class="card-text">{{ item.description }}</p>
          <a href="{% url 'website:auction_detail' item.id %}" class="btn btn-primary">View Details</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

AuctionHouse/userProfile/templates/userProfile/update_slot.html
{% extends 'base.html' %}


{% block content %}




    <style>
        body {
            font-family: Arial, sans-serif;
            background: transparent;
            margin: 0;
            padding: 0;
        }

        .slot-container {
            max-width: 500px;
            width: 100%;
            margin: 50px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
        }

        .slot-container  form {
            width: 100%;
        }
        label {
            font-weight: bold;
        }

        input,
        select,
        textarea {
            width: 100%;
            padding: 8px;
            margin: 5px 0;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }


        input[type="submit"] {
            margin-left: 50px;
            width: 80%;
            background-color: #4caf50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
        }

        input[type="submit"]:hover {
            background-color: #45a049;
        }
    </style>

    <div class="slot-container">
        <h2>Update New Slot</h2>

        <form action="" method="POST">
        {% csrf_token %}
        {{form.day.label}}
        {{form.day}}

        {{form.start_time.label}}
        {{form.start_time}}

        {{form.end_time.label}}
        {{form.end_time}}
        
        {{form.message.label}}
        {{form.message}}

        {{form.meet_link.label}}
        {{form.meet_link}}

        {{form.max_user.label}}
        {{form.max_user}}

        <input type="submit" value="Update" />
        </form>
    </div>





{% endblock %}